---
title: "realData"
output: html_document
---



```{r,eval=T}

library(reticulate)
```

```{python,eval=T}

import os
os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID" 
os.environ["CUDA_VISIBLE_DEVICES"] = ""
#os.environ["OM_NUM_THREADS"]="2"

```



```{r setup, include=T}
set.seed(1)
knitr::opts_chunk$set(echo = TRUE)
source("src/packages.R")
source("src/functions.R")
source_python("src/cIndex.py")
source_python("src/dsmScript.py")
source_python('src/deephitter.py')
source_python("src/cIndex.py")
#tf$config$threading$set_intra_op_parallelism_threads(1)
#tf$config$threading$set_inter_op_parallelism_threads(1)



#set.seed(2)

epo=2
bsize=512
min_delta = 10^-7
patience = 1
iteration=5


eval_support<-T
source_python('src/getSUP.py')








########################
###sharedHyperparams
########################

layer1<-50
layer2<-50
layer3<-25
layer4<-25
drpt<-0.5

```






```{r modelsSUPPORT,eval=eval_support}





start_time <- Sys.time()
BrierIPAList<-list()
cScore<-list()


data<- as.data.frame(do.call(cbind, getSupportPycox()))
colnames(data)[ncol(data)-1]<-'time'
colnames(data)[ncol(data)]<-'status'
data<-as.data.frame(model.matrix(~.,data)[,-1])
data<-as.data.frame(sapply(data, function(x) (x - min(x, na.rm = T)) / (max(x, na.rm = T) - min(x, na.rm=T))))


covs<-colnames(data)


#split training/testing
samp<-sample(seq(1,nrow(data),by=1), floor(nrow(data)*.80)) 
trainOG<-data[samp,]
test<-data[-samp,-c(ncol(data))]
fullTest<-data[-samp,,drop=F]




pos=1
for(iter in 1:iteration){
  
  
  samp<-sample(seq(1,nrow(trainOG),by=1) , nrow(trainOG),replace = T) 
  train<-trainOG[samp,]
  
  times<-seq(from=0,
             to=max(test$time),
             length.out = 200
  )
  times<-times[-c(1,length(times))]
  
  
  ######################
  ###casebase + splines
  ######################
  mod_cb_glm <- fitSmoothHazard(status~bs(time)+.-time,
                                data = train,
                                time = "time",
                                event="status",
                                ratio = 100
  )
  
  glmAbsRisk<-as.data.frame(absoluteRisk(mod_cb_glm,time=times,newdata=test,type="CI"))
  rownames(glmAbsRisk)<-glmAbsRisk$time
  #prepare to run through riskRegression
  glmProper<- t(glmAbsRisk[-1,-1])
  class(glmProper)<-c("tunnel",class(glmProper))
  
  ######################
  ###DeepSurv
  ######################
  coxnn<-deepsurv(Surv(time, status) ~ .,data = train, frac = 0.2, activation = "relu",
                  num_nodes = c(layer1,layer2,layer3,layer4,), dropout = drpt,
                  early_stopping = TRUE, epochs = epo,
                  batch_size = bsize,device = "cpu",best_weights=T,
                  patience = patience,min_delta=min_delta,batch_norm = F,
                  learning_rate = 0.001,lr_decay=10^-7)
  coxnnsurv<- predict(coxnn,newdata = test,type="survival")
  colnames(coxnnsurv)<-seq(0,1,length.out = ncol(coxnnsurv))
  cnnCleaned<-pyProcess(coxnnsurv,times=times)
  colnames(cnnCleaned)<-seq(0,1,length.out = ncol(cnnCleaned))
  
  ######################
  ###Deephit
  ######################
  source_python('deephitter.py')
  hitnnSurv=fitDeephit(train,fullTest,bsize,epo)
  hitnnSurv<-t(hitnnSurv)
  colnames(hitnnSurv)<-seq(0,1,length.out = ncol(hitnnSurv))
  deephitCleaned<-pyProcess(hitnnSurv,times=times)
  colnames(deephitCleaned)<-seq(0,1,length.out = ncol(deephitCleaned))
  py_run_string("del fitDeephit")
  rm(fitDeephit)
  
  ######################
  ###PMNN splines
  ######################
  covars_input<-layer_input(shape=c(length(colnames(mod_cb_glm$data))-2+3),
                            name = 'main_input'
  )
  covars_output<-covars_input%>% #layer_batch_normalization()%>%
    layer_dense(units=layer1,use_bias = T,activation = 'relu')%>%
    layer_dropout(drpt)%>%
    layer_dense(units=layer2,use_bias = T,activation = 'relu')%>%
    layer_dropout(drpt)%>%
    layer_dense(units=layer3,use_bias = T,activation = 'relu')%>%
    layer_dropout(drpt)%>%
    layer_dense(units=layer4,use_bias = T,activation = 'relu')%>%
    layer_dropout(drpt)%>%
    layer_dense(units=1,use_bias = T)
  
  pmnn<-pmnnModel(features=colnames(mod_cb_glm$data)[-ncol(mod_cb_glm$data)],
                  feature_input = covars_input,
                  feature_output = covars_output,
                  originalData = mod_cb_glm$data,
                  offset=mod_cb_glm$offset,
                  timeVar = "time",
                  eventVar= "status"
  )
  
  fit<-fitSmoothHazSpline(pmnn,epochs=epo,batch_size = bsize,verbose=0)
  annPreds<-aarSplines(fit,
                       times=times,
                       x_test=test
  )
  rownames(annPreds)<-annPreds[,1]
  annProper<- t(annPreds[,-1])
  class(annProper)<-c("tunnel",class(annProper))
  
  
  
  
  ######################
  ###coxph
  ######################
  cox<-coxph(Surv(time, status) ~ ., data = train,x=T)
  
  
  ######################
  ###PMNN
  ######################
  covars_input<-layer_input(shape=c(length(colnames(mod_cb_glm$data))-2),
                            name = 'main_input')
  
  covars_output<-covars_input%>% #layer_batch_normalization()%>%
    layer_dense(units=layer1,use_bias = T,activation = 'relu')%>%
    layer_dropout(drpt)%>%
    layer_dense(units=layer2,use_bias = T,activation = 'relu')%>%
    layer_dropout(drpt)%>%
    layer_dense(units=layer3,use_bias = T,activation = 'relu')%>%
    layer_dropout(drpt)%>%
    layer_dense(units=layer4,use_bias = T,activation = 'relu')%>%
    layer_dropout(drpt)%>%
    layer_dense(units=1,use_bias = T)
  
  pmnn<-pmnnModel(features=colnames(mod_cb_glm$data)[-ncol(mod_cb_glm$data)],
                  feature_input = covars_input,
                  feature_output = covars_output,
                  originalData = mod_cb_glm$data,
                  offset=mod_cb_glm$offset,
                  timeVar = "time",
                  eventVar= "status"
  )
  
  fit<-fitSmoothHaz(pmnn,epochs=epo,batch_size = bsize,verbose=0)
  annPreds<-aar(fit,
                times=times,
                x_test=test
  )
  
  rownames(annPreds)<-annPreds[,1]
  annProperpoly<- t(annPreds[,-1])
  class(annProperpoly)<-c("tunnel",class(annProperpoly)) 
  
  
  
  ######################
  ###IPA calculation
  ######################
  brierFinalResults <- Score(list("Cox_Lin" = cox,'CB_Logi'=glmProper,
                                  'DeepSurv'=cnnCleaned,'DeepHit'=deephitCleaned,
                                  'PMNN_Spline'=annProper,'PMNN_Poly'=annProperpoly),
                             data =fullTest, 
                             formula = Hist(time, status != 0) ~ 1, summary = c("risks","IPA","ibs"), 
                             se.fit = FALSE, metrics = "brier", contrasts = FALSE, times = times)
  BrierIPAList[[pos]]<-brierFinalResults$Brier$score
  
  
  
  ######################
  ###C-Index
  ######################
  tempTims<-as.numeric(colnames(annProper))
  tempTims<-head(tempTims, -15)
  tempTims<-tail(tempTims, -10)
  cScoreTemp<-matrix(NA,nrow=length(tempTims),ncol=7)
  
  et_train<-as.matrix(train)
  et_test<-as.matrix(fullTest[,c(11,10)])
  colnames(cScoreTemp)<-c('times', "Cox_Lin",'CB_Logi','DeepSurv','DeepHit',
                          'PMNN_Spline','PMNN_Poly')
  cScoreTemp[,1]<- tempTims
  
  ### Cox is not calculated, so abrisk is calculated here.
  a<-survfit(cox, newdata=fullTest,times=times)
  rownames(a$surv)<-a$time
  coxlinSurv<-pyProcess(t(a$surv),times=times)
  colnames(coxlinSurv)<-seq(0,1,length.out = ncol(coxlinSurv))
  riskList<-list(coxlinSurv,
                 glmProper,
                 cnnCleaned,
                 deephitCleaned,
                 annProper,
                 annProperpoly
  )
  
  cScore[[pos]]<-cIndexSummary(et_train=et_train
                               , et_test=et_test,
                               riskList=riskList,
                               cScore=cScoreTemp
  )
  pos=pos+1
  saveRDS(BrierIPAList,'100supBrier.rds')
  saveRDS(cScore,'100supcidx.rds')
  
} 



ggplot(data=brierFinalResults$Brier$score, aes(x=times,y=Brier,col=model))+
  geom_line()
ggplot(data=brierFinalResults$Brier$score, aes(x=times,y=IPA,col=model))+
  geom_line()

end_time <- Sys.time()

end_time-start_time


```






```{r modelsMETABRIC,eval=eval_metabric}



start_time <- Sys.time()


#pycox<-reticulate::import("pycox")
#numpy<-reticulate::import("numpy")
#a<-pycox$datasets$metabric$read_df
#b<-numpy$asarray(a)


############################
###Data clean and prep
############################
metabric<-getMetabric()
colnames(metabric)[ncol(metabric)-1]<-'time'
colnames(metabric)[ncol(metabric)]<-'status'
data<-as.data.frame(model.matrix(~.,metabric)[,-1])
data<-as.data.frame(sapply(data, function(x) (x - min(x, na.rm = T)) / (max(x, na.rm = T) - min(x, na.rm=T))))
covs<-colnames(data)

samp<-sample(seq(1,nrow(data),by=1), floor(nrow(data)*.80)) 
trainOG<-data[samp,]
test<-data[-samp,-c(ncol(data))]

fullTest<-data[-samp,,drop=F]

############################
###Prep Loop
############################
BrierIPAList<-list()
cScore<-list()
pos=1


for(iter in 1:iteration){
  
  ############################
  ###Bootstrap samples
  ############################  
  samp<-sample(seq(1,nrow(trainOG),by=1) , nrow(trainOG),replace = T) 
  train<-trainOG[samp,]
  
  times<-seq(from=0,
             to=max(test$time),
             length.out = 200
  )
  times<-times[-c(1,length(times))]
  times<-unique(times)
  
  ############################
  ###DSM
  ############################  
  source_python('dsmScript.py')
  dsmSurv<-dsmfitter(train=train,fullTest=fullTest,bsize=bsize,epochs=epo,tPos=ncol(train)-2,ePos=ncol(train)-1)
  #sometimes, dsm fails to converge so we keep trying until it succeeds
  if((sum(is.na(dsmSurv))==ncol(dsmSurv)*nrow(dsmSurv))){
    dsmSurv<-dsmfitter(train=train,fullTest=fullTest,bsize=bsize,epochs=epo,tPos=ncol(train)-2,ePos=ncol(train)-1)
    py_run_string("del dsmfitter")
    rm(dsmfitter)
    iteration<-iteration+1
    next
  }
  colnames(dsmSurv) <-seq(0.01,1,by=0.01)
  dsmSurvProper<-pyProcess(dsmSurv,times=times)
  colnames(dsmSurvProper) <-seq(0,1,length.out = ncol(dsmSurvProper))
  py_run_string("del dsmfitter")
  rm(dsmfitter)
  
  ############################
  ###casebase + splines
  ############################  
  mod_cb_glm <- fitSmoothHazard(status~bs(time)+.-time,
                                data = train,
                                time = "time",
                                event="status",
                                ratio = 100
  )
  
  glmAbsRisk<-absoluteRisk(mod_cb_glm,time=times,newdata=test,type="CI")
  glmAbsRisk<-as.data.frame(glmAbsRisk)
  rownames(glmAbsRisk)<-glmAbsRisk$time
  glmProper<- t(glmAbsRisk[-1,-1])
  class(glmProper)<-c("tunnel",class(glmProper))
  
  
  ############################
  ###DeepSurv
  ############################  
  coxnn<-deepsurv(Surv(time, status) ~ .,data = train, frac = 0.2, activation = "relu",
                  num_nodes = c(layer1,layer2,layer3,layer4), dropout = drpt,
                  early_stopping = TRUE, epochs = epo,
                  batch_size = bsize,device = "cpu",best_weights=T,
                  patience = patience,min_delta=min_delta,batch_norm = F,
                  learning_rate = 0.001,lr_decay=10^-7)
  
  coxnnsurv<- predict(coxnn,newdata = test,type="survival")
  colnames(coxnnsurv)<-seq(0,1,length.out = ncol(coxnnsurv))
  cnnCleaned<-pyProcess(coxnnsurv,times=times)
  colnames(cnnCleaned)<-seq(0,1,length.out = ncol(cnnCleaned))
  ############################
  ###Deephit
  ############################  
  source_python('deephitter.py')
  hitnnSurv=fitDeephit(train,fullTest,bsize,10)
  hitnnSurv<-t(hitnnSurv)
  colnames(hitnnSurv)<-seq(0,1,length.out = ncol(hitnnSurv))
  deephitCleaned<-pyProcess(hitnnSurv,times=times)
  colnames(deephitCleaned)<-seq(0,1,length.out = ncol(deephitCleaned))
  py_run_string("del fitDeephit")
  rm(fitDeephit)
  
  ############################
  ###PMNNsplines
  ############################  
  covars_input<-layer_input(shape=c(length(colnames(mod_cb_glm$data))-2+3),
                            name = 'main_input'
  )
  covars_output<-covars_input%>% 
    layer_dense(units=layer1,use_bias = T,activation = 'relu')%>%
    layer_dropout(drpt)%>%
    layer_dense(units=layer2,use_bias = T,activation = 'relu')%>%
    layer_dropout(drpt)%>%
    layer_dense(units=layer3,use_bias = T,activation = 'relu')%>%
    layer_dropout(drpt)%>%
    layer_dense(units=layer4,use_bias = T,activation = 'relu')%>%
    layer_dropout(drpt)%>%
    layer_dense(units=1,use_bias = T)
  
  pmnn<-pmnnModel(features=colnames(mod_cb_glm$data)[-ncol(mod_cb_glm$data)],
                  feature_input = covars_input,
                  feature_output = covars_output,
                  originalData = mod_cb_glm$data,
                  offset=mod_cb_glm$offset,
                  timeVar = "time",
                  eventVar= "status"
  )
  
  fit<-fitSmoothHazSpline(pmnn,epochs=epo,batch_size = bsize,verbose=0)
  annPreds<-aarSplines(fit,
                       times=times,
                       x_test=test
  )
  
  rownames(annPreds)<-annPreds[,1]
  annProper<- t(annPreds[,-1])
  class(annProper)<-c("tunnel",class(annProper))
  
  
  
  
  ############################
  ###coxph
  ############################  
  cox<-coxph(Surv(time, status) ~ ., data = train,x=T)
  
  ############################
  ###PMNN
  ############################  
  covars_input<-layer_input(shape=c(length(colnames(mod_cb_glm$data))-2),
                            name = 'main_input')
  
  covars_output<-covars_input%>% #layer_batch_normalization()%>%
    layer_dense(units=layer1,use_bias = T,activation = 'relu')%>%
    layer_dropout(drpt)%>%
    layer_dense(units=layer2,use_bias = T,activation = 'relu')%>%
    layer_dropout(drpt)%>%
    layer_dense(units=layer3,use_bias = T,activation = 'relu')%>%
    layer_dropout(drpt)%>%
    layer_dense(units=layer4,use_bias = T,activation = 'relu')%>%
    layer_dropout(drpt)%>%
    layer_dense(units=1,use_bias = T)
  
  pmnn<-pmnnModel(features=colnames(mod_cb_glm$data)[-ncol(mod_cb_glm$data)],
                  feature_input = covars_input,
                  feature_output = covars_output,
                  originalData = mod_cb_glm$data,
                  offset=mod_cb_glm$offset,
                  timeVar = "time",
                  eventVar= "status"
  )
  fit<-fitSmoothHaz(pmnn,epochs=epo,batch_size = bsize,verbose=0)
  annPreds<-aar(fit,
                times=times,
                x_test=test
  )
  rownames(annPreds)<-annPreds[,1]
  annProperpoly<- t(annPreds[,-1])
  class(annProperpoly)<-c("tunnel",class(annProperpoly)) 
  ############################
  ###Brier Score
  ############################  
  brierFinalResults <- Score(list("Cox_Lin" = cox,'CB_Logi'=glmProper,
                                  'DeepSurv'=cnnCleaned,'DeepHit'=deephitCleaned,
                                  'PMNN_Spline'=annProper,'PMNN_Poly'=annProperpoly,
                                  'dsm'=dsmSurvProper),
                             data =fullTest, 
                             formula = Hist(time, status != 0) ~ 1, summary = c("risks","IPA","ibs"), 
                             se.fit = FALSE, metrics = "brier", contrasts = FALSE, times = times)
  BrierIPAList[[pos]]<-brierFinalResults$Brier$score
  
  
  
  ############################
  ###C-Index
  ############################  
  tempTims<-   as.numeric(colnames(annProper))
  tempTims<-head(tempTims, -15)
  tempTims<-tail(tempTims, -10)
  cScoreTemp<-matrix(NA,nrow=length(tempTims),ncol=8)
  et_train<-as.matrix(train)
  et_test<-as.matrix(fullTest[,c(11,10)])
  colnames(cScoreTemp)<-c('times', "Cox_Lin",'CB_Logi','DeepSurv','DeepHit',
                          'PMNN_Spline','PMNN_Poly','dsm')
  
  
  cScoreTemp[,1]<- tempTims
  
  a<-survfit(cox, newdata=fullTest,times=times)
  rownames(a$surv)<-a$time
  coxlinSurv<-pyProcess(t(a$surv),times=times)
  colnames(coxlinSurv)<-seq(0,1,length.out = ncol(coxlinSurv))
  riskList<-list(coxlinSurv,
                 glmProper,
                 cnnCleaned,
                 deephitCleaned,
                 annProper,
                 annProperpoly
  )
  
  cScore[[pos]]<-cIndexSummary(et_train=et_train
                               , et_test=et_test,
                               riskList=riskList,
                               cScore=cScoreTemp
  )
  saveRDS(BrierIPAList,'100MetaBrier.rds')
  saveRDS(cScore,'100Metacidx.rds')
  pos=pos+1
  
} 
end_time <- Sys.time()

end_time-start_time

ggplot(data=brierFinalResults$Brier$score, aes(x=times,y=Brier,col=model))+
  geom_line()
ggplot(data=brierFinalResults$Brier$score, aes(x=times,y=IPA,col=model))+
  geom_line()

```



```{r ERSPCproofofconcept,eval=F}

data<-ERSPC
colnames(data)<-c("ScrArm","time","status")

mod_cb_glm <- fitSmoothHazard(status~.,
                              data =data,
                              time = "time",
                              event="status",
                              ratio = 100
)




covars_input<-layer_input(shape=c(length(colnames(mod_cb_glm$data))-2),
                          name = 'main_input')

covars_output<-covars_input%>% #layer_batch_normalization()%>%
  layer_dense(units=1,use_bias = T)

pmnn<-pmnnModel(features=colnames(mod_cb_glm$data)[-ncol(mod_cb_glm$data)],
                feature_input = covars_input,
                feature_output = covars_output,
                originalData = mod_cb_glm$data,
                offset=mod_cb_glm$offset,
                timeVar = "time",
                eventVar= "status",
                optimizer= 'rmsprop'
)


fit<-fitSmoothHaz(pmnn,epochs=12000,#15000
                  batch_size = 159893,#159893,#
                  verbose=0,monitor = "loss",val_split=0)
times<-seq(0,max(data$time),by=0.01)
get_weights(fit$model)
coef(mod_cb_glm)
annPreds<-aar(fit,
              times=times,
              x_test=data[1,]
)
#absoluteRisk(mod_cb_glm,time=times,newdata=data[1,],type="CI")

plot(annPreds,type="l")
lines(absoluteRisk(mod_cb_glm,time=times,newdata=data[1,],type="CI"))

results<-data.frame(intercept=c(coef(mod_cb_glm)[1],get_weights(fit$model)[[2]][1]),
                    ScrArm=c(coef(mod_cb_glm)[2],get_weights(fit$model)[[1]][1,1]),
                    time=c(coef(mod_cb_glm)[3],get_weights(fit$model)[[1]][2,1]))
rownames(results)<-c("Casebase","PMNN")
results<-round(results,2)

saveRDS(results,"../paper/figures/proofOfConceptWeights.rds")

```



```{r}

sessionInfo()

```