---
title: "flchain"
output: html_document
params:
  epo: 2000
  patience: 10
  iteration: 100
  layer1: 12
  layer2: 12
  layer3: 100
  layer4: 100
  drpt: 0.1
  lr: 0.01
---

```{r}
# First load reticulate , then initialize python environment for CUDA (I turn it off as we only had one gpu and the 4 analyses were run in parallel)
library(reticulate)

```

```{python}

import os
os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID" 
os.environ["CUDA_VISIBLE_DEVICES"] = ""

```


```{r setup, include=T}
set.seed(1)
knitr::opts_chunk$set(echo = TRUE)
source("src/packages.R")
source("src/functions.R")
library(reticulate)
eval_flchain<-T

source_python("src/cIndex.py")

##########################
###Shared Hyperparameters
##########################
min_delta = 0
epo=as.numeric(params$epo)
patience <- as.numeric(params$patience)
iteration<-as.numeric(params$iteration)
reoptimize=T
finalFit=T
```


# 3 fold cross validation to select best hyperparameters, average performance on a test set.

```{r flchainPrep,eval=TRUE,hide=FALSE}
##############################
### Process data to prepare for analysis
##############################
library(survival)
flchain<-flchain
preData<-data.frame(age=as.numeric(flchain$age),
                    sex=as.factor(flchain$sex),
                    flc=as.numeric(flchain$kappa)+as.numeric(flchain$lambda),
                    creatine=as.numeric(flchain$creatinine),
                    mgus=as.numeric(flchain$mgus),
                    time=as.numeric(flchain$futime),
                    status=as.numeric(flchain$death)
)

modData<-as.data.frame(model.matrix(~.,preData)[,-1])
data<-as.data.frame(apply(modData,2,as.numeric))
spec = c(train = .85, test = .15)
g = sample(cut(
  seq(nrow(data)), 
  nrow(data)*cumsum(c(0,spec)),
  labels = names(spec)
))
res = split(data, g)

saveRDS(res$test,"cvData/flchainTest.rds")


k=3
klist<-list()
data<-res$train
for(i in 1:k){
  spec = c(train = .85, val = .15)
  g = sample(cut(
    seq(nrow(data)), 
    nrow(data)*cumsum(c(0,spec)),
    labels = names(spec)
  ))
  klist[[i]]= split(data, g)
}
saveRDS(klist,"cvData/flchainCV.rds")




```



```{r setFixedHyperparameters,eval=TRUE,hide=FALSE}
##################################
###Set up hyperparameter search space
##################################

klist<-readRDS("cvData/flchainCV.rds")

lr=c(0.001,0.01)
drpt=c(0.01,0.05,0.1)
layer1=c(50,75,100)
layer2=c(10,25,50)
nBatch=c(100,500)
actv=c("relu","linear")#
alp=c(0,0.5,1)

```

```{r hyperOpDsurv,eval=TRUE,hide=FALSE}

###############################
### optimize hyperparameters for DeepSurv
###############################
klist<-readRDS("cvData/flchainCV.rds")
source_python('src/dsurv.py')
bestDS<-optimDeepSurv(klist,lr,drpt,layer1,layer2,nBatch,actv)

```

```{r optimDeepHit,eval=TRUE,hide=FALSE}

###############################
### optimize hyperparameters for DeepHit
###############################
klist<-readRDS("cvData/flchainCV.rds")
bestDH<-optimDeepHit(klist,lr,drpt,layer1,layer2,nBatch,actv,alp)

```


```{r hyperopcbnn,eval=TRUE,hide=FALSE}

###############################
### optimize hyperparameters for CBNN
###############################
klist<-readRDS("cvData/flchainCV.rds")
cbnnPerformance<-optimCBNN(klist,lr,drpt,layer1,layer2,nBatch,actv)

```


```{r winners,eval=TRUE,hide=FALSE}


###############################
### save the best performaning hyperparameter sets
###############################
winners<-list(cbnn=cbnnPerformance,
              ds=bestDS,
              dh=bestDH)

saveRDS(winners,"cvData/flchainWins.rds")

```

```{r bestFits,finalFit}

#####################################
### run 100 fold bootstrap on the training set for each method
#####################################

#prepare data
winners<-readRDS("cvData/flchainWins.rds")
klist<-readRDS("cvData/flchainCV.rds")
data<-rbind(klist[[1]]$train,klist[[1]]$val)


#initialize data
start_time <- Sys.time()
BrierIPAList<-list()
cScore<-list()
AUClist<-list()
pos<-1

# split training validation sets
spec = c(train = .85, validate = .15)
g = sample(cut(
  seq(nrow(data)), 
  nrow(data)*cumsum(c(0,spec)),
  labels = names(spec)
))
res = split(data, g)


while (pos <= iteration) {
  
  #prepare data
  trainOG<-res$train
  numSamp<-nrow(trainOG)
  samp<-sample(seq(1,nrow(trainOG),by=1) , nrow(trainOG),replace = T) 
  train<-trainOG[samp,]
  val<-res$validate
  sds<-sapply(train, function(x) (sd(x)))
  means<-sapply(train, function(x) (mean(x)))
  maxTime<-max(train$time)
  fullTest<-readRDS("cvData/flchainTest.rds")
  test<-fullTest[,-c(ncol(data))]
  
  #normalize data
  test<-normalizer(fullTest,means,sds,maxTime)[,-c(ncol(data))]
  fullTest<-normalizer(fullTest,means,sds,maxTime)
  val<-normalizer(res$validate,means,sds,maxTime)
  train<-normalizer(train,means,sds,maxTime)
  
  #prepare data for linear model
  linModelTrain<-as.data.frame(rbind(train,val))
  times<-seq(from=min(test$time),
             to=max(test$time),
             length.out = 82
  )
  times<-head(times, -1)
  times<-tail(times, -1)
  
  
  
  #########################
  ###casebase+splines
  ##########################
  mod_cb_glm <- casebase::fitSmoothHazard(status~bs(time)+.-time,
                                          data = linModelTrain,
                                          time = "time",
                                          event= "status",
                                          ratio = 100
  )
  
  glmAbsRisk<-as.data.frame(absoluteRisk(mod_cb_glm,time=times,newdata=test,type="CI"))
  rownames(glmAbsRisk)<-glmAbsRisk$time
  glmProper<- t(glmAbsRisk[-1,-1])
  class(glmProper)<-c("tunnel",class(glmProper))
  
  
  
  #############################
  ###DEEPSURV
  #############################
  
  lr=winners$ds$lr
  drpt=winners$ds$drpt
  layer1=winners$ds$layer1
  layer2=winners$ds$layer2
  bsize=ceiling(nrow(train)/winners$ds$nBatch)
  actv=winners$ds$actv
  
  
  source_python('src/dsurv.py')
  ctrain<-train
  ctrain$time<- train$time
  
  
  coxnnsurv=fitDeepSurv(ctrain,fullTest,bsize,epochs=epo,valida=val,patience=patience,min_delta=min_delta,drpt=drpt,lay1=layer1,lay2=layer2,lr=lr,actv=actv)
  coxnnsurv<-t(coxnnsurv)
  
  cnnCleaned<-pyProcess(coxnnsurv,times=times)
  colnames(cnnCleaned)<-times
  py_run_string("del fitDeepSurv")
  rm(fitDeepSurv)
  
  
  #############################
  ###DEEPHIT
  #############################
  lr=winners$dh$lr
  drpt=winners$dh$drpt
  layer1=winners$dh$layer1
  layer2=winners$dh$layer2
  bsize=ceiling(nrow(train)/winners$dh$nBatch)
  actv=winners$dh$actv
  alp=winners$dh$alp
  source_python('src/deephitter.py')
  hitnnSurv=fitDeephit(train,fullTest,bsize,epochs=epo,valida=val,patience=patience,min_delta=min_delta,drpt=drpt,lay1=layer1,lay2=layer2,lr=lr,actv=actv,alp=alp)
  hitnnSurv<-t(hitnnSurv)
  deephitCleaned<-pyProcess(hitnnSurv,times=times)
  colnames(deephitCleaned)<-times
  py_run_string("del fitDeephit")
  rm(fitDeephit)
  
  
  
  ############################
  ###coxph
  ############################  
  cox<-coxph(Surv(time, status) ~ ., data = linModelTrain,x=T)
  
  
  #############################
  ###CBNN
  #############################
  tempTrain<-train
  train<-sampleCaseBase(data = as.data.frame(train),time="time",event="status",ratio=100)
  valcb<-sampleCaseBase(data = as.data.frame(val),time="time",event="status",ratio=100)
  val<-list(list(as.matrix(valcb[,-c(ncol(valcb)-1,ncol(valcb))]),
                 as.matrix(valcb[,ncol(valcb),drop=F])),
            as.matrix(valcb[,ncol(valcb)-1,drop=F]))
  
  val[[1]][[2]]<-rep(train$offset[1],nrow(val[[1]][[1]]))   
  lr=winners$cbnn$lr
  drpt=winners$cbnn$drpt
  layer1=winners$cbnn$layer1
  layer2=winners$cbnn$layer2
  bsize=c(floor(nrow(train)/winners$cbnn$nBatch))
  actv=winners$cbnn$actv
  
  
  currentTime<-Sys.time() 
  covars_input<-layer_input(shape=c(length(colnames(mod_cb_glm$data))-2),
                            name = 'main_input')
  
  covars_output<-covars_input%>%
    layer_dense(units=layer1,use_bias = T)%>%
    layer_activation(activation = actv)%>%
    layer_dropout(drpt)%>%
    layer_dense(units=layer2,use_bias = T)%>%
    layer_activation(activation = actv)%>%
    layer_dropout(drpt)%>%
    layer_dense(units=1,use_bias = T)
  
  cbnn<-cbnnModel(features=colnames(train)[-ncol(train)],
                  feature_input = covars_input,
                  feature_output = covars_output,
                  originalData = train,
                  offset=train$offset,
                  timeVar = "time",
                  eventVar= "status",optimizer=optimizer_adam(learning_rate = lr)
  )
  
  fit<-fitSmoothHaz(cbnn,
                    epochs=epo,
                    batch_size=bsize,
                    verbose=0,
                    monitor="val_loss",
                    #val_split=0.2,
                    min_delta=min_delta,
                    patience=patience,val=val)
  annPreds<-aar(fit,
                times=times,
                x_test=test
  )
  
  rownames(annPreds)<-annPreds[,1]
  annProperpoly<- t(annPreds[,-1])
  class(annProperpoly)<-c("tunnel",class(annProperpoly)) 
  
  
  
  ############################
  ###Brier Score
  ############################  
  brierFinalResults <- Score(list("Cox_Lin" = cox,'CB_Logi'=glmProper,
                                  'DeepSurv'=cnnCleaned,'DeepHit'=deephitCleaned,
                                  'CBNN_Poly'=annProperpoly),
                             data =fullTest, 
                             formula = Hist(time, status != 0) ~ 1, summary = c("risks","IPA","ibs"), 
                             se.fit = FALSE, metrics = c("auc", "brier"), contrasts = FALSE, times = times)
  BrierIPAList[[pos]]<-brierFinalResults$Brier$score
  AUClist[[pos]]<-brierFinalResults$AUC$score
  
  ggplot(data=brierFinalResults$Brier$score, aes(x=times,y=IPA,col=model))+
    geom_line()#+coord_cartesian(ylim=c(-0.1,0.2))
  rm(fit,cbnn,covars_input,covars_output)
  #######################
  ###Cox 
  ######################
  a<-survfit(cox, newdata=fullTest,times=times)
  rownames(a$surv)<-a$time
  coxlinSurv<-pyProcess(t(a$surv),times=times)
  colnames(coxlinSurv)<-seq(0,1,length.out = ncol(coxlinSurv))
  
  
  ######################
  ###C-Index
  ######################
  
  riskList<-list(coxlinSurv,
                 glmProper,
                 cnnCleaned,
                 deephitCleaned,
                 annProperpoly
  )
  
  
  tempTims<-   as.numeric(colnames(annProperpoly))
  tempTims<-head(tempTims, -1)
  tempTims<-tail(tempTims, -1)
  cScoreTemp<-matrix(NA,nrow=length(tempTims),ncol=length(riskList)+1)
  et_train<-as.matrix(tempTrain)[,c(ncol(tempTrain),ncol(tempTrain)-1)]
  et_test<-as.matrix(fullTest[,c(ncol(fullTest),ncol(fullTest)-1)])
  colnames(cScoreTemp)<-c('times', "Cox_Lin",'CB_Logi','DeepSurv','DeepHit',
                          'cbnn')
  cScoreTemp[,1]<- tempTims
  
  cScore[[pos]]<-cIndexSummary(et_train=et_train,
                               et_test=et_test,
                               riskList=riskList,
                               cScore=cScoreTemp
  )
  print(paste("current iter:",pos))
  saveRDS(BrierIPAList,'results/100flchainBrier.rds')
  saveRDS(cScore,'results/100flchaincidx.rds')
  saveRDS(AUClist,'results/100flchainAuc.rds')
  pos=pos+1
  
}


```




```{r plotflchain}

#######################
###plot IPA results
#######################

BrierIPAList<-readRDS('results/100flchainBrier.rds')

ipaSims=data.frame(model=BrierIPAList[[1]]$model,times=BrierIPAList[[1]]$times)
brierSims=data.frame(model=BrierIPAList[[1]]$model,times=BrierIPAList[[1]]$times)
ibsSims=data.frame(model=BrierIPAList[[1]]$model,times=BrierIPAList[[1]]$times)
ibsTable<-as.data.frame(matrix(data=NA,nrow=100,ncol=length(unique(BrierIPAList[[1]]$model))))
colnames(ibsTable)<-unique(BrierIPAList[[1]]$model)
count=1
for(sim in BrierIPAList){
  ipaSims<-cbind(ipaSims, sim$IPA)
  brierSims<-cbind(brierSims,sim$Brier)
  ibsSims<-cbind(ibsSims,sim$IBS)
  for(mod in colnames(ibsTable)){
    
    ibsTable[count,which(mod ==colnames(ibsTable))]<-sim$IBS[sim$model==mod & sim$time==max(sim$time)]
    
  }
  count<-count+1
}
ibsTable<-na.omit(ibsTable)
ibsOverall<-data.frame(mean=apply(ibsTable,2,mean),sd = apply(ibsTable,2,sd))
ibsOverall
ipaSummary<-statCalcSim(ipaSims)
brierSummary<-statCalcSim(brierSims)
ibsSummary<-statCalcSim(ibsSims)
ipa<-plotPerformance(ipaSummary,method="IPA",iterations=iteration  )
brier<-plotPerformance(brierSummary,method="BS",iterations=iteration )
ibs<-plotPerformance(ibsSummary,method="IBS",iterations=iteration )

ipa+coord_cartesian(ylim=c(-0.1,0.5))
#end_time-start_time



```


```{r auc}
#######################
###plot AUC results
#######################
AUClist<-readRDS('results/100flchainAuc.rds')
aucSims=data.frame(model=AUClist[[1]]$model,times=AUClist[[1]]$times)
for(sim in AUClist){
  aucSims<-cbind(aucSims,sim$AUC)
  
}
aucSummary<-statCalcSim(aucSims)
auc<-plotPerformance(aucSummary,method="AUC",iterations=iteration )

auc

```

```{r}


#######################
###plot C-index results
#######################

cidxList<-readRDS('results/100flchaincidx.rds')


temp<-melt(setDT(as.data.frame(cidxList[[1]])), id.vars = c("times"), variable.name = "model")
cidxSims=data.frame(model=temp$model,times=temp$times)


count=1
for(sim in cidxList){
  cidxSims<-cbind(cidxSims, melt(setDT(as.data.frame(sim)), id.vars = c("times"), variable.name = "model")$value)
  
  count<-count+1
}

cidxSummary<-statCalcSim(cidxSims)
cidxC<-plotPerformance(cidxSummary,method="C-Index",iterations=iteration  )
cidxC


```
