---
title: "iterSim"
output: html_document
params:
  epo: 2000
  patience: 10
  iteration: 1
  layer1: 50
  layer2: 50
  layer3: 25
  layer4: 25
  drpt: 0.1
---

```{r}

library(reticulate)
```

```{python}

import os
os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID" 
os.environ["CUDA_VISIBLE_DEVICES"] = ""


```


```{r setup, include=T}
set.seed(1)
knitr::opts_chunk$set(echo = TRUE)
source("src/packages.R")
source("src/functions.R")
eval_support<-T
source_python('src/getSUP.py')
source_python("src/cIndex.py")
source_python("src/dsmScript.py")
source_python('src/deephitter.py')
##########################
###Shared Hyperparameters
##########################
bsize=512
min_delta = 0
epo=as.numeric(params$epo)
patience <- as.numeric(params$patience)
iteration<-as.numeric(params$iteration)
layer1<-as.numeric(params$layer1)
layer2<-as.numeric(params$layer2)
layer3<-as.numeric(params$layer3)
layer4<-as.numeric(params$layer4)
drpt<-as.numeric(params$drpt)


easysim<-T
numSamp<-2000
```



```{r easySimpletests,eval=easysim}
start_time <- Sys.time()






  
  #############################
  ###Data generation
  #############################
  
  cov<-data.frame(id=1:numSamp,
                  z1=c(rep(1,numSamp/2),rep(0,numSamp/2)),
                  z2=c(rnorm(numSamp/2,10,0.5),rnorm(numSamp/2,0,0.5)),
                  z3=c(rnorm(numSamp/2,-3,0.5),rnorm(numSamp/2,8,0.5))
  )
  
  dat <- simsurv(dist = "exponential",
                 lambdas =.05,
                 betas = c(z1 = 1,z2=1,z3=1),
                 x = cov,
                 tdefunction = "log",
                 maxt = 1
  )
  colnames(dat)<-c("id","time","status")
  samp<-sample(seq(1,nrow(dat),by=1), floor(nrow(dat)*(0.1))) #random censoring
  dat$status[samp]<-0
  # Merge the simulated event times onto covariate data frame
  data <- merge(cov, dat)
  covs<-colnames(data)
  data<-data[,-1]



 spec = c(train = .7, test = .1, validate = .2)
 
 g = sample(cut(
   seq(nrow(data)), 
   nrow(data)*cumsum(c(0,spec)),
   labels = names(spec)
 ))
 
 res = split(data, g)


trainOG<-res$train

test<-res$test[,-c(ncol(data))]

fullTest<-res$test

val<-res$validate

valcb<-sampleCaseBase(data = val,time="time",event="status",ratio=100)
valcb$offset<-0
valcbtensor<-list(list(as.matrix(valcb[,-c(ncol(valcb)-1,ncol(valcb))]),as.matrix(valcb[,ncol(valcb),drop=F])),as.matrix(valcb[,ncol(valcb)-1,drop=F]))

numSamp<-nrow(trainOG)




BrierIPAList<-list()
cScore<-list()

pos<-1

while (pos <= iteration) {
  
  
  
  #############################
  ###Data generation
  #############################
  
  cov<-data.frame(id=1:numSamp,
                  z1=c(rep(1,numSamp/2),rep(0,numSamp/2)),
                  z2=c(rnorm(numSamp/2,10,0.5),rnorm(numSamp/2,0,0.5)),
                  z3=c(rnorm(numSamp/2,-3,0.5),rnorm(numSamp/2,8,0.5))
  )
  
  dat <- simsurv(dist = "exponential",
                 lambdas =.05,
                 betas = c(z1 = 0.5,z2=0.5,z3=0.5),
                 x = cov,
                 tdefunction = "log",
                 maxt = 1
  )
  colnames(dat)<-c("id","time","status")
  samp<-sample(seq(1,nrow(dat),by=1), floor(nrow(dat)*(0.1))) #random censoring
  dat$status[samp]<-0
  # Merge the simulated event times onto covariate data frame
  data <- merge(cov, dat)
  covs<-colnames(data)
  data<-data[,-1]
  train<-data
  #test<-data[-samp,-c(ncol(data))]
  #fullTest<-data[-samp,,drop=F]
  times<-seq(from=min(test$time)+0.000001,
             to=max(test$time)-0.000001,
             length.out = 100
  ) 
  
  ##########################
  ###DSM
  ##########################
  source_python('src/dsmScript.py')
  dsmSurv<-dsmfitter(train=train,fullTest=fullTest,bsize=bsize,epochs=epo,val=val,times=times,tPos=ncol(train)-2,ePos=ncol(train)-1)
  if((sum(is.na(dsmSurv))==ncol(dsmSurv)*nrow(dsmSurv))){
    
    dsmSurv<-dsmfitter(train=train,fullTest=fullTest,bsize=bsize,epochs=epo,val=val,times=times)
    py_run_string("del dsmfitter")
    rm(dsmfitter)
    next
  }
  colnames(dsmSurv) <-times
  dsmSurvProper<-pyProcess(dsmSurv,times=times)
  colnames(dsmSurvProper) <-seq(0,1,length.out = ncol(dsmSurvProper))
  py_run_string("del dsmfitter")
  rm(dsmfitter)
  
  ##########################
  ###casebase optimal model
  ##########################
  final_mod_cb_glm <- fitSmoothHazard(status~z1+z2+z3,#z1:z2:z3+z1+z2+z3,+z1:z3+z1:z2:z3
                                      data = train,
                                      time = "time",
                                      event="status",
                                      ratio = 100
  )
  
  summary(final_mod_cb_glm)
  tglmAbsRisk<-absoluteRisk(final_mod_cb_glm,time=times,newdata=test,type="CI")
  tglmAbsRisk<-as.data.frame(tglmAbsRisk)
  rownames(tglmAbsRisk)<-tglmAbsRisk$time
  trueGlmProper<- t(tglmAbsRisk[-1,-1])
  
  class(trueGlmProper)<-c("tunnel",class(trueGlmProper))
  
  
  
  
  #########################
  ###casebase+splines
 ##########################
    mod_cb_glm <- fitSmoothHazard(status~bs(time)+.-time,
                                data = train,
                                time = "time",
                                event="status",
                                ratio = 100
  )
  
  glmAbsRisk<-as.data.frame(absoluteRisk(mod_cb_glm,time=times,newdata=test,type="CI"))
  rownames(glmAbsRisk)<-glmAbsRisk$time
  #prepare to run through riskRegression
  glmProper<- t(glmAbsRisk[-1,-1])
  class(glmProper)<-c("tunnel",class(glmProper))
  
  
  # 
  # 
  # ############################
  # ###DeepSurv
  # ############################  
   
  
  source_python('src/dsurv.py')
  #need to break ties
  tiebreakTrain<-train
  
  #while(length(unique(tiebreakTrain$time))/length(tiebreakTrain$time)!=1 ){
  #tiebreakTrain<-train
  #tiebreakTrain$time<-tiebreakTrain$time+runif(nrow(tiebreakTrain),0,1/10000000000)
  #}
  

  coxnnsurv=fitDeepSurv(tiebreakTrain,fullTest,bsize,epochs=epo,valida=val,patience=patience,min_delta=min_delta,drpt=drpt,lay1=layer1,lay2=layer2,lay3=layer3,lay4=layer4)
  coxnnsurv<-t(coxnnsurv)
  #colnames(coxnnsurv)<-seq(0,1,length.out = ncol(coxnnsurv))
  cnnCleaned<-pyProcess(coxnnsurv,times=times)
  colnames(cnnCleaned)<-times#seq(0,1,length.out = ncol(cnnCleaned))
  py_run_string("del fitDeepSurv")
  rm(fitDeepSurv)
  
  # coxnn<-deepsurv(Surv(time, status) ~ .,data = train, frac = 0.2, activation = "relu",
  #                 num_nodes = c(layer1,layer2,layer3,layer4), dropout = drpt,
  #                 early_stopping = TRUE, epochs = epo,
  #                 batch_size = bsize,device = "cpu",best_weights=T,
  #                 patience = patience,min_delta=min_delta,batch_norm = F,
  #                 learning_rate = 0.001,lr_decay=10^-7)
  # 
  # coxnnsurv<- predict(coxnn,newdata = test,type="survival")
  # colnames(coxnnsurv)<-seq(0,1,length.out = ncol(coxnnsurv))
  # cnnCleaned<-pyProcess(coxnnsurv,times=times)
  # colnames(cnnCleaned)<-seq(0,1,length.out = ncol(cnnCleaned))
  ############################
  ###Deephit
  ############################  
    source_python('src/deephitter.py')
  hitnnSurv=fitDeephit(train,fullTest,bsize,epo,valida=val,patience=patience,min_delta=min_delta,drpt=drpt,lay1=layer1,lay2=layer2,lay3=layer3,lay4=layer4)
  hitnnSurv<-t(hitnnSurv)
  #colnames(hitnnSurv)<-seq(0,1,length.out = ncol(hitnnSurv))
  deephitCleaned<-pyProcess(hitnnSurv,times=times)
  colnames(deephitCleaned)<-seq(0,1,length.out = ncol(deephitCleaned))
  py_run_string("del fitDeephit")
  rm(fitDeephit)
  # source_python('src/deephitter.py')
  # hitnnSurv=fitDeephit(train,fullTest,bsize,epo,patience=patience,min_delta=min_delta,drpt=drpt)
  # hitnnSurv<-t(hitnnSurv)
  # colnames(hitnnSurv)<-seq(0,1,length.out = ncol(hitnnSurv))
  # deephitCleaned<-pyProcess(hitnnSurv,times=times)
  # colnames(deephitCleaned)<-seq(0,1,length.out = ncol(deephitCleaned))
  # py_run_string("del fitDeephit")
  # rm(fitDeephit)
  # 
  ############################
  ###PMNNsplines
  ############################  
  covars_input<-layer_input(shape=c(length(colnames(mod_cb_glm$data))-2+3),
                            name = 'main_input'
  )
  covars_output<-covars_input%>% #layer_batch_normalization()%>%
    layer_dense(units=layer1,use_bias = T,activation = 'tanh')%>%
    layer_dropout(drpt)%>%
    layer_dense(units=layer2,use_bias = T,activation = 'tanh')%>%
    layer_dropout(drpt)%>%
    layer_dense(units=layer3,use_bias = T,activation = 'tanh')%>%
    layer_dropout(drpt)%>%
    layer_dense(units=layer4,use_bias = T,activation = 'tanh')%>%
    layer_dropout(drpt)%>%
    layer_dense(units=1,use_bias = T)
  
  pmnn<-pmnnModel(features=colnames(mod_cb_glm$data)[-ncol(mod_cb_glm$data)],
                  feature_input = covars_input,
                  feature_output = covars_output,
                  originalData = mod_cb_glm$data,
                  offset=mod_cb_glm$offset,
                  timeVar = "time",
                  eventVar= "status",optimizer=optimizer_adam(learning_rate = 0.0001)
  )


  fit<-fitSmoothHazSpline(pmnn,
                          epochs=epo,
                          batch_size=bsize,
                          verbose=0,
                          monitor="val_loss",
                          #val_split=0.2,
                          min_delta=min_delta,
                          patience=patience,val=valcbtensor)
  
   annPreds<-aarSplines(fit,
                       times=times,
                       x_test=test
  )
  rownames(annPreds)<-annPreds[,1]
  annProper<- t(annPreds[,-1])
  class(annProper)<-c("tunnel",class(annProper))
  
  
  
  
  
  
  
  ######################
  ###coxph
  ######################
  cox<-coxph(Surv(time, status) ~ z1+z2+z3, data = train,x=T)
  
  
  ######################
  ###PMNN  
  ######################
  covars_input<-layer_input(shape=c(length(colnames(mod_cb_glm$data))-2),
                            name = 'main_input')
  
  covars_output<-covars_input%>% #layer_batch_normalization()%>%
    layer_dense(units=layer1,use_bias = T,activation = 'tanh')%>%
    layer_dropout(drpt)%>%
    layer_dense(units=layer2,use_bias = T,activation = 'tanh')%>%
    layer_dropout(drpt)%>%
    layer_dense(units=layer3,use_bias = T,activation = 'tanh')%>%
    layer_dropout(drpt)%>%
    layer_dense(units=layer4,use_bias = T,activation = 'tanh')%>%
    layer_dropout(drpt)%>%
    layer_dense(units=1,use_bias = T)
  
  pmnn<-pmnnModel(features=colnames(mod_cb_glm$data)[-ncol(mod_cb_glm$data)],
                  feature_input = covars_input,
                  feature_output = covars_output,
                  originalData = mod_cb_glm$data,
                  offset=mod_cb_glm$offset,
                  timeVar = "time",
                  eventVar= "status",optimizer=optimizer_adam(learning_rate = 0.0001)
  )
  
  fit<-fitSmoothHaz(pmnn,
                    epochs=epo,
                    batch_size=bsize,
                    verbose=0,
                    monitor="val_loss",
                    val_split=0.2,
                    min_delta=min_delta,
                    patience=patience,val=valcbtensor)
  annPreds<-aar(fit,
                times=times,
                x_test=test
  )
  
  rownames(annPreds)<-annPreds[,1]
  annProperpoly<- t(annPreds[,-1])
  class(annProperpoly)<-c("tunnel",class(annProperpoly)) 
  
  class(annProperpoly)<-c("tunnel",class(annProperpoly)) 
  brierFinalResults <- Score(list("Cox_Lin" = cox,
                                  'CB_Logi'=glmProper,
                                  'DeepSurv'=cnnCleaned,
                                  'DeepHit'=deephitCleaned,
                                  'PMNN_Spline'=annProper,
                                  'Optimal'=trueGlmProper,
                                  'PMNN_Poly'=annProperpoly,
                                  'dsm'=dsmSurvProper) ,#'dsm'=dsmCleaned,
                                  data =fullTest, 
                             formula = Hist(time, status != 0) ~ 1, summary = c("risks","IPA","ibs"), 
                             se.fit = FALSE, metrics = "brier", contrasts = FALSE, times = times)
  BrierIPAList[[pos]]<-brierFinalResults$Brier$score
  
  
  #######################
  ###Cox 
  ######################
  a<-survfit(cox, newdata=fullTest,times=times)
  rownames(a$surv)<-a$time
  coxlinSurv<-pyProcess(t(a$surv),times=times)
  colnames(coxlinSurv)<-seq(0,1,length.out = ncol(coxlinSurv))
  
  
  ######################
  ###C-Index
  ######################

  riskList<-list(coxlinSurv,
                 glmProper,
                 cnnCleaned,
                 deephitCleaned,
                 annProper,
                 trueGlmProper,
                 annProperpoly,
                 dsmSurvProper
  )
  

  tempTims<-   as.numeric(colnames(annProper))
  tempTims<-head(tempTims, -1)
  tempTims<-tail(tempTims, -1)
  cScoreTemp<-matrix(NA,nrow=length(tempTims),ncol=length(riskList)+1)
  et_train<-as.matrix(train)[,c(5,4)]
  et_test<-as.matrix(fullTest[,c(5,4)])
  colnames(cScoreTemp)<-c('times', "Cox_Lin",'CB_Logi','DeepSurv','DeepHit',
                          'PMNN_Spline','Optimal','PMNN_Poly','dsm')#,'dsm')
  cScoreTemp[,1]<- tempTims


  
  
  cScore[[pos]]<-cIndexSummary(et_train=et_train,
                               et_test=et_test,
                               riskList=riskList,
                               cScore=cScoreTemp
  )

  saveRDS(BrierIPAList,'results/100easyBrier.rds')
  saveRDS(cScore,'results/100easycidx.rds')
  pos<-pos+1
}
end_time <- Sys.time()




```

```{r}

  ggplot(data=brierFinalResults$Brier$score, aes(x=times,y=IPA,col=model))+
  geom_line()+coord_cartesian(ylim=c(-1,1))

```
