---
title: "Support"
output: html_document
params:
  epo: 2000
  patience: 5
  iteration: 2
  layer1: 50
  layer2: 25
  layer3: 100
  layer4: 100
  drpt: 0.1
  lr: 0.001
---



```{r,eval=T}
set.seed(1)
library(reticulate)
```

```{python,eval=T}

import os
os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID" 
os.environ["CUDA_VISIBLE_DEVICES"] = ""
#os.environ["OM_NUM_THREADS"]="2"

```



```{r setup, include=T}

knitr::opts_chunk$set(echo = TRUE)
source("src/packages.R")
source("src/functions.R")
eval_support<-T
source_python('src/getSUP.py')
source_python("src/cIndex.py")
source_python("src/dsmScript.py")
source_python('src/deephitter.py')
##########################
###Shared Hyperparameters
##########################
bsize=512
min_delta = 10^-7
epo=as.numeric(params$epo)
patience <- as.numeric(params$patience)
iteration<-as.numeric(params$iteration)
layer1<-10#as.numeric(params$layer1)
layer2<-5#as.numeric(params$layer2)
layer3<-14*3#as.numeric(params$layer3)
layer4<-14*2#as.numeric(params$layer4)
drpt<-as.numeric(params$drpt)
lr=as.numeric(params$lr)

```






```{r modelsSUPPORT,eval=eval_support}





start_time <- Sys.time()
BrierIPAList<-list()
cScore<-list()


data<- as.data.frame(do.call(cbind, getSupportPycox()))

colnames(data)[ncol(data)-1]<-'time'
colnames(data)[ncol(data)]<-'status'

data$time<-data$time/max(data$time)
for(i in c(2,5,6,7)){#3,4,
data[, i]<-as.factor(data[, i])
}
data<-as.data.frame(model.matrix(~.,data)[,-1])
#data<-as.data.frame(sapply(data, function(x) (x - min(x, na.rm = T)) / (max(x, na.rm = T) - min(x, na.rm=T))))

covs<-colnames(data)
names(data)[ncol(data)-2] <- paste("z", ncol(data)-2, sep="")
names(data)[ncol(data)-1]<-"time"
names(data)[ncol(data)]<-"status"
  data<-data[,-1]
  toDiv<-max(data$time)

  data$time<-data$time/toDiv
#split training/testing

 spec = c(train = .7, test = .15, validate = .15)
 
 g = sample(cut(
   seq(nrow(data)), 
   nrow(data)*cumsum(c(0,spec)),
   labels = names(spec)
 ))
 
 res = split(data, g)


trainOG<-res$train

test<-res$test[,-c(ncol(data))]

fullTest<-res$test

val<-res$validate






  times<-seq(from=min(test$time)+0.000001,
             to=max(test$time)-0.000001,
             length.out = 100
  )

pos<-1

while (pos <= iteration) {
  

  
  samp<-sample(seq(1,nrow(trainOG),by=1) , nrow(trainOG),replace = T) 
  train<-trainOG[samp,]
  sds<-sapply(train, function(x) (sd(x)))
means<-sapply(train, function(x) (mean(x)))
test<-normalizer(res$test,means,sds)[,-c(ncol(data))]
fullTest<-normalizer(res$test,means,sds)
val<-normalizer(res$validate,means,sds)
valcb<-sampleCaseBase(data = val,time="time",event="status",ratio=100)

valcb$offset<-0
valcbtensor<-list(list(as.matrix(valcb[,-c(ncol(valcb)-1,ncol(valcb))]),as.matrix(valcb[,ncol(valcb),drop=F])),as.matrix(valcb[,ncol(valcb)-1,drop=F]))

train<-normalizer(train,means,sds)

  
  #########################
  ###casebase+splines
 ##########################
    mod_cb_glm <- fitSmoothHazard(status~bs(time)+.-time,
                                data = train,
                                time = "time",
                                event="status",
                                ratio = 100
  )
  
  glmAbsRisk<-as.data.frame(absoluteRisk(mod_cb_glm,time=times,newdata=test,type="CI"))
  rownames(glmAbsRisk)<-glmAbsRisk$time
  #prepare to run through riskRegression
  glmProper<- t(glmAbsRisk[-1,-1])
  class(glmProper)<-c("tunnel",class(glmProper))
  
  
  # 
  # 
  # ############################
  # ###DeepSurv
  # ############################  
   
  
  source_python('src/dsurv.py')
  #need to break ties
  
  #while(length(unique(tiebreakTrain$time))/length(tiebreakTrain$time)!=1 ){
  #tiebreakTrain<-train
  #tiebreakTrain$time<-tiebreakTrain$time+runif(nrow(tiebreakTrain),0,1/10000000000)
  #}
  
  coxnnsurv=fitDeepSurv(train,fullTest,bsize,epochs=epo,valida=val,patience=patience,min_delta=min_delta,drpt=drpt,lay1=layer1,lay2=layer2,lr=lr,actv="relu")
  coxnnsurv<-t(coxnnsurv)
  #colnames(coxnnsurv)<-seq(0,1,length.out = ncol(coxnnsurv))
  cnnCleaned<-pyProcess(coxnnsurv,times=times)
  colnames(cnnCleaned)<-times#seq(0,1,length.out = ncol(cnnCleaned))
  py_run_string("del fitDeepSurv")
  rm(fitDeepSurv)
  
  # coxnn<-deepsurv(Surv(time, status) ~ .,data = train, frac = 0.2, activation = "relu",
  #                 num_nodes = c(layer1,layer2,layer3,layer4), dropout = drpt,
  #                 early_stopping = TRUE, epochs = epo,
  #                 batch_size = bsize,device = "cpu",best_weights=T,
  #                 patience = patience,min_delta=min_delta,batch_norm = F,
  #                 learning_rate = 0.001,lr_decay=10^-7)
  # 
  # coxnnsurv<- predict(coxnn,newdata = test,type="survival")
  # colnames(coxnnsurv)<-seq(0,1,length.out = ncol(coxnnsurv))
  # cnnCleaned<-pyProcess(coxnnsurv,times=times)
  # colnames(cnnCleaned)<-seq(0,1,length.out = ncol(cnnCleaned))
  ############################
  ###Deephit
  ############################  
    source_python('src/deephitter.py')
  hitnnSurv=fitDeephit(train,fullTest,floor(nrow(train)/100),epochs=epo,valida=val,patience=patience,min_delta=min_delta,drpt=drpt,lay1=layer1,lay2=layer2,lr=lr,actv='relu',alp=0)
  hitnnSurv<-t(hitnnSurv)
  #colnames(hitnnSurv)<-seq(0,1,length.out = ncol(hitnnSurv))
  deephitCleaned<-pyProcess(hitnnSurv,times=times)
  colnames(deephitCleaned)<-seq(0,1,length.out = ncol(deephitCleaned))
  py_run_string("del fitDeephit")
  rm(fitDeephit)
  # source_python('src/deephitter.py')
  # hitnnSurv=fitDeephit(train,fullTest,bsize,epo,patience=patience,min_delta=min_delta,drpt=drpt)
  # hitnnSurv<-t(hitnnSurv)
  # colnames(hitnnSurv)<-seq(0,1,length.out = ncol(hitnnSurv))
  # deephitCleaned<-pyProcess(hitnnSurv,times=times)
  # colnames(deephitCleaned)<-seq(0,1,length.out = ncol(deephitCleaned))
  # py_run_string("del fitDeephit")
  # rm(fitDeephit)
  # # 
  # ############################
  # ###cbnnsplines
  # ############################  
  #   valcbtensor[[1]][[2]]<-rep(mod_cb_glm$offset[1],nrow(valcbtensor[[1]][[1]]))
  # covars_input<-layer_input(shape=c(length(colnames(mod_cb_glm$data))-2+3),
  #                           name = 'main_input'
  # )
  # covars_output<-covars_input%>% #layer_batch_normalization()%>%
  #   layer_dense(units=layer1,use_bias = T,activation = 'relu')%>%
  #   layer_dropout(drpt)%>%
  #   layer_dense(units=layer2,use_bias = T,activation = 'relu')%>%
  #   layer_dropout(drpt)%>%
  #   #layer_dense(units=layer3,use_bias = T,activation = 'relu')%>%
  #   #layer_dropout(drpt)%>%
  #   #layer_dense(units=layer4,use_bias = T,activation = 'relu')%>%
  #   #layer_dropout(drpt)%>%
  #   layer_dense(units=1,use_bias = T)
  # 
  # cbnn<-cbnnModel(features=colnames(mod_cb_glm$data)[-ncol(mod_cb_glm$data)],
  #                 feature_input = covars_input,
  #                 feature_output = covars_output,
  #                 originalData = mod_cb_glm$data,
  #                 offset=mod_cb_glm$offset,
  #                 timeVar = "time",
  #                 eventVar= "status",optimizer=optimizer_adam(learning_rate = lr)
  # )
  # 
  # 
  # 
  # fit<-fitSmoothHazSpline(cbnn,
  #                         epochs=epo,
  #                         batch_size=floor(nrow(mod_cb_glm$data)/100),
  #                         verbose=0,
  #                         monitor="val_loss",
  #                         #val_split=0.2,
  #                         min_delta=min_delta,
  #                         patience=patience,val=valcbtensor)
  # 
  #  annPreds<-aarSplines(fit,
  #                      times=times,
  #                      x_test=test
  # )
  # rownames(annPreds)<-annPreds[,1]
  # annProper<- t(annPreds[,-1])
  # class(annProper)<-c("tunnel",class(annProper))
  # 
  # 
  # 
  
  ############################
  ###coxph
  ############################  
  cox<-coxph(Surv(time, status) ~ ., data = train,x=T)
  
   
  ######################
  ###cbnn  
  ######################
  covars_input<-layer_input(shape=c(length(colnames(mod_cb_glm$data))-2),
                            name = 'main_input')
  
  covars_output<-covars_input%>% #layer_batch_normalization()%>%
    #layer_dropout(drpt)%>%
    layer_dense(units=layer1,use_bias = T,activation = 'relu')%>%
    layer_dropout(drpt)%>%
    layer_dense(units=layer2,use_bias = T,activation = 'relu')%>%
    layer_dropout(drpt)%>%
    #layer_dense(units=layer3,use_bias = T,activation = 'relu')%>%
    #layer_dropout(drpt)%>%
    #layer_dense(units=layer4,use_bias = T,activation = 'relu')%>%
    #layer_dropout(drpt)%>%
    layer_dense(units=1,use_bias = T)

  
  cbnn<-cbnnModel(features=colnames(mod_cb_glm$data)[-ncol(mod_cb_glm$data)],
                  feature_input = covars_input,
                  feature_output = covars_output,
                  originalData = mod_cb_glm$data,
                  offset=mod_cb_glm$offset,
                  timeVar = "time",
                  eventVar= "status",optimizer=optimizer_adam(learning_rate = lr)
  )
  
  fit<-fitSmoothHaz(cbnn,
                    epochs=epo,
                    batch_size=floor(nrow(mod_cb_glm$data)/100),
                    verbose=0,
                    monitor="val_loss",
                    #val_split=0.2,
                    min_delta=min_delta,
                    patience=patience,val=valcbtensor)
  annPreds<-aar(fit,
                times=times,
                x_test=test
  )
  
  rownames(annPreds)<-annPreds[,1]
  annProperpoly<- t(annPreds[,-1])
  class(annProperpoly)<-c("tunnel",class(annProperpoly)) 
  ############################
  ###Brier Score
  ############################  
 
  
  brierFinalResults <- Score(list("Cox_Lin" = cox,
                                  'CB_Logi'=glmProper,
                                  'DeepSurv'=cnnCleaned,
                                  'DeepHit'=deephitCleaned,
                                  #'cbnn_Spline'=annProper,
                                  'cbnn_Poly'=annProperpoly),
                             data =fullTest, 
                             formula = Hist(time, status != 0) ~ 1, summary = c("risks","IPA","ibs"), 
                             se.fit = FALSE, metrics = "brier", contrasts = FALSE, times = times)
  BrierIPAList[[pos]]<-brierFinalResults$Brier$score
    ggplot(data=brierFinalResults$Brier$score, aes(x=times,y=IPA,col=model))+
  geom_line()+coord_cartesian(ylim=c(-0.1,0.2))
     rm(cbnn,fit,annPreds,covars_input,covars_output)
  ######################
  ###Cox
  ######################
  a<-survfit(cox, newdata=fullTest,times=times)
  rownames(a$surv)<-a$time
  coxlinSurv<-pyProcess(t(a$surv),times=times)
  colnames(coxlinSurv)<-seq(0,1,length.out = ncol(coxlinSurv))
  
  
  ######################
  ###C-Index
  ######################

  riskList<-list(coxlinSurv,
                 glmProper,
                 cnnCleaned,
                 deephitCleaned,
                 annProper,
                 annProperpoly
  )
  

  tempTims<-   as.numeric(colnames(annProper))
  tempTims<-head(tempTims, -1)
  tempTims<-tail(tempTims, -1)
  cScoreTemp<-matrix(NA,nrow=length(tempTims),ncol=length(riskList)+1)
  et_train<-as.matrix(train)[,c(16,15)]
  et_test<-as.matrix(fullTest[,c(16,15)])
  colnames(cScoreTemp)<-c('times', "Cox_Lin",'CB_Logi','DeepSurv','DeepHit',
                          'cbnn_Spline','cbnn_Poly')#,'dsm')
  cScoreTemp[,1]<- tempTims


  
  
  cScore[[pos]]<-cIndexSummary(et_train=et_train,
                               et_test=et_test,
                               riskList=riskList,
                               cScore=cScoreTemp
  )
  
  #saveRDS(BrierIPAList,'results/100supBrier.rds')
  #saveRDS(cScore,'results/100supcidx.rds')
  pos<-pos+1
  gc()
}






ggplot(data=brierFinalResults$Brier$score, aes(x=times,y=Brier,col=model))+
  geom_line()
ggplot(data=brierFinalResults$Brier$score, aes(x=times,y=IPA,col=model))+
  geom_line()

end_time <- Sys.time()

end_time-start_time


```



```{r}

  ggplot(data=brierFinalResults$Brier$score, aes(x=times,y=IPA,col=model))+
  geom_line()+coord_cartesian(ylim=c(-0.1,0.2))


```


```{r}

sessionInfo()

```